name: survey_kit
description: Create beautiful surveys with Flutter (inspired by iOS ResearchKit Surveys)
version: 0.1.2
homepage: https://quickbirdstudios.com
repository: https://github.com/quickbirdstudios/survey_kit
issue_tracker: https://github.com/quickbirdstudios/survey_kit/issues

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  bloc: ^8.0.3
  camera: ^0.10.5+9
  collection: ^1.15.0
  cupertino_icons: ^1.0.2
  currency_text_input_formatter: ^2.1.10
  equatable: ^2.0.3
  firebase_core: ^2.21.0
  firebase_crashlytics: ^3.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_platform_widgets: ^6.0.0
  go_router: ^6.0.1
  google_fonts: ^4.0.4
  image_picker: ^1.0.8
  intl: ^0.18.0
  json_annotation: ^4.0.1
  lottie: ^2.2.0
  permission_handler: ^11.0.1
  provider: ^6.1.0
  uuid: ^3.0.7
  video_player: ^2.8.1

dependency_overrides:
  intl: ^0.18.0

dev_dependencies:
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.1.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/fancy_checkmark.json
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
